version: '2'
services:
  hotspot_mongo:
    image: mongo
    container_name: hotspot_mongo
    hostname: hotspot_mongo
    ports:
      - 27017
    volumes:
      - /home/myroot/docker.shell/hotspot/data:/data/db
    command: mongod --directoryperdb   
    
    
  hotspot:
    depends_on:
      - hotspot_mongo
    image: ewnchui/geohotspot
    container_name: hotspot 
    hostname: hotspot
    ports:
      - 1337
    volumes:
      - ${COMPOSEROOT}/hotspot/conf/server.coffee:/usr/src/app/config/env/production.coffee
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates